export { default as About } from './About/About'
export { default as Category } from './Category/Category'
export { default as Footer } from './Footer/Footer'
export { default as Header } from './Header/Header'
export { default as List } from './List/List'
